version: '3'

services:
  shewchuk-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/shewchuk-cpython:6.7.0-alpha
    volumes:
      - ./pyproject.toml:/opt/shewchuk/pyproject.toml
      - ./README.md:/opt/shewchuk/README.md
      - ./setup.py:/opt/shewchuk/setup.py
      - ./src:/opt/shewchuk/src
      - ./shewchuk:/opt/shewchuk/shewchuk
      - ./tests:/opt/shewchuk/tests
    entrypoint: pytest
