version: '3'

services:
  shewchuk-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/shewchuk-pypy:6.7.1-alpha
    volumes:
      - ./pyproject.toml:/opt/shewchuk/pyproject.toml
      - ./README.md:/opt/shewchuk/README.md
      - ./setup.py:/opt/shewchuk/setup.py
      - ./shewchuk:/opt/shewchuk/shewchuk
      - ./tests:/opt/shewchuk/tests
    entrypoint: pytest
