name: CI

on:
  push:
    branches:
      - 'master'
    tags: [ 'v*' ]
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: 'Test'
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        platform: [
          {
            os: 'macos-latest',
            python_architecture: 'x64'
          },
          {
            os: 'ubuntu-latest',
            python_architecture: 'x64'
          },
          {
            os: 'windows-latest',
            python_architecture: 'x64'
          },
          {
            os: 'windows-latest',
            python_architecture: 'x86'
          },
        ]
        include:
          - python_version: 'pypy-3.7'
            platform: { os: 'macos-latest', python_architecture: 'x64' }
          - python_version: 'pypy-3.7'
            platform: { os: 'ubuntu-latest', python_architecture: 'x64' }
          - python_version: 'pypy-3.7'
            platform: { os: 'windows-latest', python_architecture: 'x64' }
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.platform.python_architecture }}
      - name: 'Install packaging tools'
        run: python -m pip install -U pip setuptools
      - name: 'Install coverage dependencies'
        run: python -m pip install -U coverage
      - name: 'Install С++ coverage dependencies'
        run: python -m pip install -U gcovr
        if: ${{ !startsWith(matrix.python_version, 'pypy') }}
      - name: 'Install in editable mode'
        run: python -m pip -v install -e .
        env:
          CPPFLAGS: --coverage -O0
      - name: 'Install tests dependencies'
        run: python -m pip install -r requirements-tests.txt
      - name: 'Run doctests'
        run: >
          coverage run -m doctest README.md
          && coverage run --append -m pytest --doctest-modules --ignore=tests
      - name: 'Run tests'
        run: coverage run --append -m pytest
      - name: 'Collect coverage'
        run: coverage xml
      - name: 'Collect C coverage'
        run: gcovr --filter src/ --filter include/ --xml -o coverage_c.xml
        if: ${{ !startsWith(matrix.python_version, 'pypy') }}
      - name: 'Upload PyPy coverage'
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
        if: ${{ startsWith(matrix.python_version, 'pypy') }}
        continue-on-error: true
      - name: 'Upload СPython coverage'
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: false
          files: ./coverage.xml,./coverage_c.xml
        if: ${{ !startsWith(matrix.python_version, 'pypy') }}
        continue-on-error: true

  pre-deploy:
    name: 'Pre-deploy'
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref_type == 'tag'
    steps:
      - name: '_'
        run: echo "Pre-deploy step"

  build-sdist:
    name: 'Build sdist'
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 'Setup Python'
        uses: actions/setup-python@v3
      - name: 'Install packaging tools'
        run: python -m pip install -U build pip setuptools
      - name: 'Build sdist'
        run: python -m build --sdist
      - name: 'Upload sdist'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  build-wheels:
    name: 'Build wheels'
    runs-on: ${{ matrix.os }}-latest
    needs: pre-deploy
    strategy:
      matrix:
        os: ['ubuntu', 'windows', 'macos']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 'Setup Python'
        uses: actions/setup-python@v3
      - name: 'Setup QEMU'
        if: ${{ runner.os == 'Linux' }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: 'Build wheels'
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: pp*
      - name: 'Upload wheels'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./wheelhouse/*.whl

  test-distributions:
    name: Test distributions
    runs-on: ${{ matrix.platform.os }}
    needs: ['build-sdist', 'build-wheels']
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        platform: [
          {
            os: 'macos-latest',
            python_architecture: 'x64'
          },
          {
            os: 'ubuntu-latest',
            python_architecture: 'x64'
          },
          {
            os: 'windows-latest',
            python_architecture: 'x64'
          },
          {
            os: 'windows-latest',
            python_architecture: 'x86'
          },
        ]
        include:
          - python_version: 'pypy-3.7'
            platform: { os: 'macos-latest', python_architecture: 'x64' }
          - python_version: 'pypy-3.7'
            platform: { os: 'ubuntu-latest', python_architecture: 'x64' }
          - python_version: 'pypy-3.7'
            platform: { os: 'windows-latest', python_architecture: 'x64' }
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.platform.python_architecture }}
      - name: 'Download distributions'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: 'Install from distributions'
        run: python -m pip install --find-links=dist --no-deps --no-index ${{ github.event.repository.name }}

  deploy:
    name: 'Deploy'
    environment: release
    needs: test-distributions
    runs-on: ubuntu-latest
    steps:
      - name: 'Download distributions'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: 'PyPI upload'
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          packages_dir: dist
          password: ${{ secrets.PYPI_API_TOKEN }}
